### PR TITLE
Bump Runtime to 19.08

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by Lctrs** [comment]
GK is stuck in an infinite loop on launch with version 19.08 of the runtime. Don't know why.

**Comment by Erick555** [comment]
@Lctrs there are many changes here beside runtime bump. Does it happen when only runtime is updated?

**Comment by Lctrs** [comment]
> @Lctrs there are many changes here beside runtime bump. Does it happen when only runtime is updated?

Yep.

**Comment by Erick555** [comment]
@Lctrs The latest test build isn't available anymore, could you trigger an new one?

**Comment by Lctrs** [comment]
@Erick555 Here is the test build with only the runtime update.

**Comment by Erick555** [comment]
@Lctrs it seems stuck while showing splash screen - is that what you see too?

**Comment by Lctrs** [comment]
Yes.

I tried to debug things with strace but I'm not comfortable with this tool.

**Comment by Erick555** [comment]
I'm not that much familiar with it too, I don't know what's happening here.

**Comment by Lctrs** [comment]
Interesting. According to `strace`, we have the same loop of `recvmsg(38, {msg_namelen=0}, 0)         = -1 EAGAIN (Ressource temporairement non disponible)` using `18.08` but it does not stuck launching the app in this case...

**Comment by Lctrs** [comment]
The app works with Gnome Runtime `3.34`.

**Comment by Lctrs** [comment]
Will move to the Gnome Runtime as part of next update.

**Pull request closed without merging**
