### PR TITLE
Fix tarball URL

### LINKED ISSUE #2: Won't install
I can't install GitKraken due to the following error. I assume this is related to this build. It says an extra file has the wrong size.

grafik

### PR DESCRIPTION
**Pull request by jlelse**
This should fix #2

@nedrichards Or someone else, could you please look into this :wink:

### CODE REVIEW

**Comment by jlelse** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by Lctrs** [comment]
I wasn't aware of the existence of this kind of URL. Thanks a lot 👍

**Comment by jlelse** [comment]
Found this after searching for the AUR script :smile:

**Pull request merged**
