### PR TITLE
Update appdata

### LINKED ISSUE #24: Missing screenshots
https://flathub.org/apps/details/com.axosoft.GitKraken

### PR DESCRIPTION
**Pull request by Lctrs**
Close #24 .

New description has been requested by Axosoft.

Ping @bochecha, @nedrichards, @TingPing. WDYT ?

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
I think, that if that's what they want - that's what they get. Furthermore, if they want access to the repo just send us some github usernames and they can push the changes themselves ;-)

**Comment by Lctrs** [comment]
Yeah. I should have been more precise with my questions.

- Do you think there will be any problem with the rather long description ?
- Is there any problem with using .gif as screenshots ?

**Comment by nedrichards** [comment]
I don't think there will be a problem with the long description in the cases that I'm aware of.

The appdata spec says that screenshots should be PNG or JPEG https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by Lctrs** [comment]
bot, build

**Comment by Lctrs** [comment]
OK. I removed the gif screenshots. If the test build succeeds, I'll merge it.

**Comment by Lctrs** [comment]
bot, build

**Pull request merged**
