### PR TITLE
Allow access to ssh socket

### LINKED ISSUE #5: Can't connect to SSH_AGENT
It seems that the flatpak version of GK cannot use the SSH Agent for authentication.

Error message:
Fetch failed for 'origin'
error authenticating: failed connecting with agent

### PR DESCRIPTION
**Pull request by Lctrs**
Close #5

### CODE REVIEW

**Comment by Lctrs** [comment]
bot, build

**Comment by nedrichards** [comment]
fwiw this won't be able to be tested/released until flathub updates the version of flatpak on all the builders to at least 0.99.1

you might want to check into #flatpak on IRC to see how that's going - or I'll try and remember to update this when it's done.

**Comment by Lctrs** [comment]
Yeah I know.

I couldn't find anywhere the flatpak version used by the builders so I made this PR to see if it was already done. I'll check the IRC channel. Thanks.

**Comment by Lctrs** [comment]
bot, build

**Comment by Lctrs** [comment]
bot, build

**Pull request merged**
