### PR TITLE
Update to 6.0.0

### PR DESCRIPTION
**Pull request by jlelse**
Update Gitkraken to 6.0.0 and git to 2.22.0

### CODE REVIEW

**Comment by Lctrs** [comment]
I was just doing the same things 😄 Thanks !

**Comment by jlelse** [comment]
Just installed it, seems to work great :smile: Also tabs are nice :smirk:

**Comment by Lctrs** [comment]
Yeah. I just need to check something with Git compilation (it might not use the build flags defined in freedesktop runtime). Otherwise, LGTM.

**Comment by Lctrs** [comment]
Thanks @jlelse !

**Pull request merged**
